# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/shield/etc/bin/cmake

# The command to remove a file.
RM = /opt/shield/etc/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/shield/etc/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/fs/users/kazymai/mybackup/Save/PC/work/Shield/shield

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/fs/users/kazymai/mybackup/Save/PC/work/Shield/shield

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/shield/etc/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/shield/etc/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/fs/users/kazymai/mybackup/Save/PC/work/Shield/shield/CMakeFiles /opt/fs/users/kazymai/mybackup/Save/PC/work/Shield/shield/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/fs/users/kazymai/mybackup/Save/PC/work/Shield/shield/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HADGEN

# Build rule for target.
HADGEN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HADGEN
.PHONY : HADGEN

# fast build rule for target.
HADGEN/fast:
	$(MAKE) -f hadgen/CMakeFiles/HADGEN.dir/build.make hadgen/CMakeFiles/HADGEN.dir/build
.PHONY : HADGEN/fast

#=============================================================================
# Target rules for targets named parse

# Build rule for target.
parse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parse
.PHONY : parse

# fast build rule for target.
parse/fast:
	$(MAKE) -f hadgen/parse/CMakeFiles/parse.dir/build.make hadgen/parse/CMakeFiles/parse.dir/build
.PHONY : parse/fast

#=============================================================================
# Target rules for targets named parse_run

# Build rule for target.
parse_run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parse_run
.PHONY : parse_run

# fast build rule for target.
parse_run/fast:
	$(MAKE) -f hadgen/parse/CMakeFiles/parse_run.dir/build.make hadgen/parse/CMakeFiles/parse_run.dir/build
.PHONY : parse_run/fast

#=============================================================================
# Target rules for targets named SHIELD

# Build rule for target.
SHIELD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SHIELD
.PHONY : SHIELD

# fast build rule for target.
SHIELD/fast:
	$(MAKE) -f shield/CMakeFiles/SHIELD.dir/build.make shield/CMakeFiles/SHIELD.dir/build
.PHONY : SHIELD/fast

#=============================================================================
# Target rules for targets named THadgen

# Build rule for target.
THadgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 THadgen
.PHONY : THadgen

# fast build rule for target.
THadgen/fast:
	$(MAKE) -f THadgen/CMakeFiles/THadgen.dir/build.make THadgen/CMakeFiles/THadgen.dir/build
.PHONY : THadgen/fast

#=============================================================================
# Target rules for targets named TShield

# Build rule for target.
TShield: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TShield
.PHONY : TShield

# fast build rule for target.
TShield/fast:
	$(MAKE) -f TShield/CMakeFiles/TShield.dir/build.make TShield/CMakeFiles/TShield.dir/build
.PHONY : TShield/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HADGEN"
	@echo "... parse"
	@echo "... parse_run"
	@echo "... SHIELD"
	@echo "... THadgen"
	@echo "... TShield"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

