//
// File generated by /opt/shield/etc//bin/rootcint at Wed Apr 29 14:22:38 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dIoptdIfsdIusersdIkazymaidImybackupdISavedIPCdIworkdIShielddIshielddITHadgendIG__Hadgen
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "G__Hadgen.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void THadgen_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_THadgen(void *p = 0);
   static void *newArray_THadgen(Long_t size, void *p);
   static void delete_THadgen(void *p);
   static void deleteArray_THadgen(void *p);
   static void destruct_THadgen(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::THadgen*)
   {
      ::THadgen *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::THadgen >(0);
      static ::ROOT::TGenericClassInfo 
         instance("THadgen", ::THadgen::Class_Version(), "./inc/THadgen.h", 30,
                  typeid(::THadgen), ::ROOT::DefineBehavior(ptr, ptr),
                  &::THadgen::Dictionary, isa_proxy, 4,
                  sizeof(::THadgen) );
      instance.SetNew(&new_THadgen);
      instance.SetNewArray(&newArray_THadgen);
      instance.SetDelete(&delete_THadgen);
      instance.SetDeleteArray(&deleteArray_THadgen);
      instance.SetDestructor(&destruct_THadgen);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::THadgen*)
   {
      return GenerateInitInstanceLocal((::THadgen*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::THadgen*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr THadgen::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *THadgen::Class_Name()
{
   return "THadgen";
}

//______________________________________________________________________________
const char *THadgen::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::THadgen*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int THadgen::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::THadgen*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void THadgen::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::THadgen*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *THadgen::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::THadgen*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void THadgen::Streamer(TBuffer &R__b)
{
   // Stream an object of class THadgen.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(THadgen::Class(),this);
   } else {
      R__b.WriteClassBuffer(THadgen::Class(),this);
   }
}

//______________________________________________________________________________
void THadgen::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class THadgen.
      TClass *R__cl = ::THadgen::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ParticlesNum", &ParticlesNum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "autoseed", &autoseed);
      TGenerator::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_THadgen(void *p) {
      return  p ? new(p) ::THadgen : new ::THadgen;
   }
   static void *newArray_THadgen(Long_t nElements, void *p) {
      return p ? new(p) ::THadgen[nElements] : new ::THadgen[nElements];
   }
   // Wrapper around operator delete
   static void delete_THadgen(void *p) {
      delete ((::THadgen*)p);
   }
   static void deleteArray_THadgen(void *p) {
      delete [] ((::THadgen*)p);
   }
   static void destruct_THadgen(void *p) {
      typedef ::THadgen current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::THadgen

/********************************************************
* /opt/fs/users/kazymai/mybackup/Save/PC/work/Shield/shield/THadgen/G__Hadgen.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableG__Hadgen();

extern "C" void G__set_cpp_environmentG__Hadgen() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("inc/THadgen.h");
  G__cpp_reset_tagtableG__Hadgen();
}
#include <new>
extern "C" int G__cpp_dllrevG__Hadgen() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* THadgen */
static int G__G__Hadgen_239_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) THadgen::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) THadgen::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) THadgen::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      THadgen::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THadgen*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) THadgen::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) THadgen::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) THadgen::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) THadgen::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   THadgen* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new THadgen[n];
     } else {
       p = new((void*) gvp) THadgen[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new THadgen;
     } else {
       p = new((void*) gvp) THadgen;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__HadgenLN_THadgen));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) THadgen::Instance());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((THadgen*) G__getstructoffset())->DoSome());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THadgen*) G__getstructoffset())->SetRandomSeed((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THadgen*) G__getstructoffset())->SetRandomSeed();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((THadgen*) G__getstructoffset())->GetRandomSeed());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((THadgen*) G__getstructoffset())->SetAutoSeed((bool) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((THadgen*) G__getstructoffset())->SetAutoSeed();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THadgen*) G__getstructoffset())->SetIncidentParticle((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((THadgen*) G__getstructoffset())->GetIncidentParticle());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THadgen*) G__getstructoffset())->SetNuclid((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((THadgen*) G__getstructoffset())->GetNuclid());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THadgen*) G__getstructoffset())->SetEnergy((Float_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((THadgen*) G__getstructoffset())->GetEnergy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((THadgen*) G__getstructoffset())->SetSystem((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((THadgen*) G__getstructoffset())->SetSystem();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((THadgen*) G__getstructoffset())->GetSystem());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((THadgen*) G__getstructoffset())->SetLAntil((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((THadgen*) G__getstructoffset())->SetLAntil();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((THadgen*) G__getstructoffset())->GetLAntil());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((THadgen*) G__getstructoffset())->SetLSTAR((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((THadgen*) G__getstructoffset())->SetLSTAR();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((THadgen*) G__getstructoffset())->GetLSTAR());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((THadgen*) G__getstructoffset())->SetLCASC((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((THadgen*) G__getstructoffset())->SetLCASC();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((THadgen*) G__getstructoffset())->GetLCASC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((THadgen*) G__getstructoffset())->SetNumStat((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((THadgen*) G__getstructoffset())->SetNumStat();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((THadgen*) G__getstructoffset())->GetNumStat());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THadgen*) G__getstructoffset())->SetAProj((Float_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((THadgen*) G__getstructoffset())->GetAProj());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THadgen*) G__getstructoffset())->SetZProj((Float_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((THadgen*) G__getstructoffset())->GetZProj());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Hadgen_239_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((THadgen*) G__getstructoffset())->FileOut((char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef THadgen G__TTHadgen;
static int G__G__Hadgen_239_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (THadgen*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((THadgen*) (soff+(sizeof(THadgen)*i)))->~G__TTHadgen();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (THadgen*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((THadgen*) (soff))->~G__TTHadgen();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* THadgen */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncG__Hadgen {
 public:
  G__Sizep2memfuncG__Hadgen(): p(&G__Sizep2memfuncG__Hadgen::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncG__Hadgen::*p)();
};

size_t G__get_sizep2memfuncG__Hadgen()
{
  G__Sizep2memfuncG__Hadgen a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceG__Hadgen() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G__HadgenLN_THadgen))) {
     THadgen *G__Lderived;
     G__Lderived=(THadgen*)0x1000;
     {
       TGenerator *G__Lpbase=(TGenerator*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__HadgenLN_THadgen),G__get_linked_tagnum(&G__G__HadgenLN_TGenerator),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__HadgenLN_THadgen),G__get_linked_tagnum(&G__G__HadgenLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__HadgenLN_THadgen),G__get_linked_tagnum(&G__G__HadgenLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableG__Hadgen() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__G__HadgenLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__HadgenLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__HadgenLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__HadgenLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__HadgenLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__G__HadgenLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__HadgenLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__HadgenLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__HadgenLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__HadgenLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__G__HadgenLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__G__HadgenLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__G__HadgenLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__G__HadgenLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__G__HadgenLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__G__HadgenLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* THadgen */
static void G__setup_memvarTHadgen(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__HadgenLN_THadgen));
   { THadgen *p; p=(THadgen*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__HadgenLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__HadgenLN_THadgen),-1,-2,2,"fInstance=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"ParticlesNum=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"autoseed=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarG__Hadgen() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTHadgen(void) {
   /* THadgen */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__HadgenLN_THadgen));
   G__memfunc_setup("Class",502,G__G__Hadgen_239_0_1, 85, G__get_linked_tagnum(&G__G__HadgenLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&THadgen::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__G__Hadgen_239_0_2, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&THadgen::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__G__Hadgen_239_0_3, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&THadgen::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__G__Hadgen_239_0_4, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&THadgen::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__HadgenLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__Hadgen_239_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__G__Hadgen_239_0_9, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&THadgen::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__G__Hadgen_239_0_10, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&THadgen::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__G__Hadgen_239_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&THadgen::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__G__Hadgen_239_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&THadgen::DeclFileLine) ), 0);
   G__memfunc_setup("THadgen",667,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__G__HadgenLN_THadgen), -1, 0, 1, 1, 4, 0, "u 'THadgen' - 11 - s", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__G__HadgenLN_THadgen), -1, 1, 1, 1, 4, 0, "u 'THadgen' - 11 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("THadgen",667,G__G__Hadgen_239_0_15, 105, G__get_linked_tagnum(&G__G__HadgenLN_THadgen), -1, 0, 0, 1, 1, 0, "", "creates a unique instance of THadgen", (void*) NULL, 0);
   G__memfunc_setup("Instance",821,G__G__Hadgen_239_0_16, 85, G__get_linked_tagnum(&G__G__HadgenLN_THadgen), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (THadgen* (*)())(&THadgen::Instance) ), 0);
   G__memfunc_setup("DoSome",583,G__G__Hadgen_239_0_17, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", "Just a test function, will be deleted in future release", (void*) NULL, 0);
   G__memfunc_setup("SetRandomSeed",1294,G__G__Hadgen_239_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - seed", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetRandomSeed",1294,G__G__Hadgen_239_0_19, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRandomSeed",1282,G__G__Hadgen_239_0_20, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetAutoSeed",1094,G__G__Hadgen_239_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'true' flag", "initially true    ", (void*) NULL, 0);
   G__memfunc_setup("SetLuxCount",1134,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "i - 'Int_t' 0 - luxcnt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLuxCount",1122,(G__InterfaceMethod) NULL, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetIncidentParticle",1934,G__G__Hadgen_239_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - jpart", "these functions may be more smart ", (void*) NULL, 0);
   G__memfunc_setup("GetIncidentParticle",1922,G__G__Hadgen_239_0_25, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNuclid",907,G__G__Hadgen_239_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - nuclid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNuclid",895,G__G__Hadgen_239_0_27, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergy",918,G__G__Hadgen_239_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "f - 'Float_t' 0 - energy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergy",906,G__G__Hadgen_239_0_29, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSystem",945,G__G__Hadgen_239_0_30, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 '0' lanti", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSystem",933,G__G__Hadgen_239_0_31, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetLAntil",880,G__G__Hadgen_239_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 '0' lantil", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLAntil",868,G__G__Hadgen_239_0_33, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetLSTAR",690,G__G__Hadgen_239_0_34, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 '0' lstar", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLSTAR",678,G__G__Hadgen_239_0_35, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetLCASC",658,G__G__Hadgen_239_0_36, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 '0' lcasc", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLCASC",646,G__G__Hadgen_239_0_37, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNumStat",1016,G__G__Hadgen_239_0_38, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 '1' nstat", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNumStat",1004,G__G__Hadgen_239_0_39, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetAProj",776,G__G__Hadgen_239_0_40, 121, -1, -1, 0, 1, 1, 1, 0, "f - 'Float_t' 0 - aproj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetAProj",764,G__G__Hadgen_239_0_41, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetZProj",801,G__G__Hadgen_239_0_42, 121, -1, -1, 0, 1, 1, 1, 0, "f - 'Float_t' 0 - zproj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetZProj",789,G__G__Hadgen_239_0_43, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GenerateEvent",1325,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ImportParticles",1570,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__HadgenLN_TObjArray), -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ImportParticles",1570,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"U 'TClonesArray' - 0 - particles C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("FileOut",696,G__G__Hadgen_239_0_47, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 0 - filename", "test function", (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~THadgen", 793, G__G__Hadgen_239_0_48, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncG__Hadgen() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalG__Hadgen() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcG__Hadgen() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__G__HadgenLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TObjArray = { "TObjArray" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TClonesArray = { "TClonesArray" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__G__HadgenLN_TGenerator = { "TGenerator" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__G__HadgenLN_THadgen = { "THadgen" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableG__Hadgen() {
  G__G__HadgenLN_TClass.tagnum = -1 ;
  G__G__HadgenLN_TBuffer.tagnum = -1 ;
  G__G__HadgenLN_TMemberInspector.tagnum = -1 ;
  G__G__HadgenLN_TObject.tagnum = -1 ;
  G__G__HadgenLN_TNamed.tagnum = -1 ;
  G__G__HadgenLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__G__HadgenLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__HadgenLN_TObjArray.tagnum = -1 ;
  G__G__HadgenLN_TClonesArray.tagnum = -1 ;
  G__G__HadgenLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__G__HadgenLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__HadgenLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__G__HadgenLN_TGenerator.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__G__HadgenLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__G__HadgenLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__G__HadgenLN_THadgen.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableG__Hadgen() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TClass);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TObject);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TNamed);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TObjArray);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TClonesArray);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TGenerator);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__HadgenLN_TMatrixTSparseDiaglEfloatgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__G__HadgenLN_THadgen),sizeof(THadgen),-1,327424,"THadgen",G__setup_memvarTHadgen,G__setup_memfuncTHadgen);
}
extern "C" void G__cpp_setupG__Hadgen(void) {
  G__check_setup_version(30051515,"G__cpp_setupG__Hadgen()");
  G__set_cpp_environmentG__Hadgen();
  G__cpp_setup_tagtableG__Hadgen();

  G__cpp_setup_inheritanceG__Hadgen();

  G__cpp_setup_typetableG__Hadgen();

  G__cpp_setup_memvarG__Hadgen();

  G__cpp_setup_memfuncG__Hadgen();
  G__cpp_setup_globalG__Hadgen();
  G__cpp_setup_funcG__Hadgen();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncG__Hadgen();
  return;
}
class G__cpp_setup_initG__Hadgen {
  public:
    G__cpp_setup_initG__Hadgen() { G__add_setup_func("G__Hadgen",(G__incsetup)(&G__cpp_setupG__Hadgen)); G__call_setup_funcs(); }
   ~G__cpp_setup_initG__Hadgen() { G__remove_setup_func("G__Hadgen"); }
};
G__cpp_setup_initG__Hadgen G__cpp_setup_initializerG__Hadgen;

