/********************************************************************
* /opt/fs/users/kazymai/mybackup/Save/PC/work/Shield/shield/THadgen/G__Hadgen.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /opt/fs/users/kazymai/mybackup/Save/PC/work/Shield/shield/THadgen/G__Hadgen.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Hadgen();
extern void G__cpp_setup_inheritanceG__Hadgen();
extern void G__cpp_setup_typetableG__Hadgen();
extern void G__cpp_setup_memvarG__Hadgen();
extern void G__cpp_setup_globalG__Hadgen();
extern void G__cpp_setup_memfuncG__Hadgen();
extern void G__cpp_setup_funcG__Hadgen();
extern void G__set_cpp_environmentG__Hadgen();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/THadgen.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__HadgenLN_TClass;
extern G__linked_taginfo G__G__HadgenLN_TBuffer;
extern G__linked_taginfo G__G__HadgenLN_TMemberInspector;
extern G__linked_taginfo G__G__HadgenLN_TObject;
extern G__linked_taginfo G__G__HadgenLN_TNamed;
extern G__linked_taginfo G__G__HadgenLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__HadgenLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__HadgenLN_TObjArray;
extern G__linked_taginfo G__G__HadgenLN_TClonesArray;
extern G__linked_taginfo G__G__HadgenLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__HadgenLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__HadgenLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__HadgenLN_TGenerator;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__HadgenLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__HadgenLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__HadgenLN_THadgen;

/* STUB derived class for protected member access */
