/********************************************************************
* /opt/fs/users/kazymai/mybackup/Save/PC/work/Shield/shield/TShield/G__Shield.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /opt/fs/users/kazymai/mybackup/Save/PC/work/Shield/shield/TShield/G__Shield.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Shield();
extern void G__cpp_setup_inheritanceG__Shield();
extern void G__cpp_setup_typetableG__Shield();
extern void G__cpp_setup_memvarG__Shield();
extern void G__cpp_setup_globalG__Shield();
extern void G__cpp_setup_memfuncG__Shield();
extern void G__cpp_setup_funcG__Shield();
extern void G__set_cpp_environmentG__Shield();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/TShield.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__ShieldLN_TClass;
extern G__linked_taginfo G__G__ShieldLN_TBuffer;
extern G__linked_taginfo G__G__ShieldLN_TMemberInspector;
extern G__linked_taginfo G__G__ShieldLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__ShieldLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ShieldLN_TClonesArray;
extern G__linked_taginfo G__G__ShieldLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__ShieldLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ShieldLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__ShieldLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__ShieldLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__ShieldLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR;
extern G__linked_taginfo G__G__ShieldLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR;
extern G__linked_taginfo G__G__ShieldLN_TGeoManager;
extern G__linked_taginfo G__G__ShieldLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR;
extern G__linked_taginfo G__G__ShieldLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ShieldLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__ShieldLN_TTree;
extern G__linked_taginfo G__G__ShieldLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__ShieldLN_shield_tree_node;
extern G__linked_taginfo G__G__ShieldLN_TShield;

/* STUB derived class for protected member access */
