set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
if(NOT DEFINED SIMPATH)
    set(SIMPATH $ENV{SIMPATH})
    set(ROOTSYS ${SIMPATH})
    set(ROOT_LIBRARY_DIR "${ROOTSYS}/lib/root")
    set(ROOT_INCLUDE_DIR "${ROOTSYS}/include/root")
    set(ROOT_CINT_EXECUTABLE "${SIMPATH}/bin/rootcint")
    set(LIBRARY_OUTPUT_PATH "${CMAKE_BINARY_DIR}/lib")
    set(configfile "config.sh")
    configure_file(cmake/config.sh.in ${configfile})

    include(IndependentMacro)
endif()

if(NOT SIMPATH)
    message(FATAL_ERROR "Fairsoft installation not found, please provide SIMPATH first")
endif()

#Option for generating code designed to be compatible with code generated by g77 and f2c.
#Don't work for first add_directory. Why?
#set(CMAKE_Fortran_FLAGS ${CMAKE_Fortran_FLAGS} "-ff2c")
